stages:          # List of stages for jobs, and their order of execution
  - test
    #   - docs # Not yet

run-test:
    stage: test
    image: python:3.11-slim-bookworm
    script:
        - pip install pytest
        - pip install .
        - python -m pytest -s test.py
    rules:
        - if: $CI_COMMIT_MESSAGE =~ /\[CI\]/