stages:
    - test
    - publish

run-test:
    stage: test
    image: python:3.11-slim-bookworm
    script:
        - pip install pytest
        - pip install .
        - python -m pytest -s test.py
    rules:
        - if: $CI_COMMIT_MESSAGE =~ /\[CI\]/

pages:
    stage: publish
    image: python:3.11-slim-bookworm
    script:
        - pip install -r requirements.txt
        - mkdocs build --site-dir public
    rules:
        - if: $CI_COMMIT_MESSAGE =~ /\[CI\]/ || $CI_COMMIT_MESSAGE =~ /\[docs\]/
    artifacts:
        when: on_success
        expire_in: 1 days
        paths:
        - public
    needs:
      - run-test

build-release:
    stage: publish
    image: python:3.11-slim-bookworm
    script:
        - pip install build twine
        - python -m build
        - twine upload dist/*.tar.gz -u __token__ -p "$PYPI_TOKEN"
    rules:
        - if: $CI_COMMIT_MESSAGE =~ /\[CI\]/ && $CI_COMMIT_MESSAGE =~ /\[release\]/
    needs:
        - run-test

# vim:set sw=4
