stages:
    - test
    - docs

run-test:
    stage: test
    image: python:3.11-slim-bookworm
    script:
        - pip install pytest
        - pip install .
        - python -m pytest -s test.py
    rules:
        - if: $CI_COMMIT_MESSAGE =~ /\[CI\]/

pages:
    stage: docs
    image: python:3.11-slim-bookworm
    script:
        - pip install mkdocs mkdocstrings mkdocstrings-python pymdown-extensions black
        - mkdocs build --site-dir public
    rules:
        - if: $CI_COMMIT_MESSAGE =~ /\[CI\]/ || $CI_COMMIT_MESSAGE =~ /\[docs\]/
    artifacts:
        when: on_success
        expire_in: 1 days
        paths:
        - public